
parameters:

  - name: usePreRelease
    type: boolean
    default: false

  - name: preBuildSteps
    type: stepList

  - name: projectPath
    type: string

  - name: tempFolderName
    type: string

  - name: projectName
    type: string

  - name: destDirectory
    type: string 

  - name: port
    type: string
    
  - name: configs
    type: object

  - name: service
    type: object

  - name: serviceTemplate
    type: string
    default: |
      [Unit]
      Description=${{ service.description }}

      [Install]
      WantedBy=multi-user.target

      [Service]
      WorkingDirectory=${{ destDirectory }}
      ExecStart=/usr/bin/dotnet ${{ destDirectory }}/${{ projectName }}.dll --urls http://localhost:${{ service.port }}
      Restart=always
      # Restart service after 10 seconds if the dotnet service crashes:
      RestartSec=10
      KillSignal=SIGINT
      SyslogIdentifier=${{ service.identifier }}
      User=www-data

stages:
  - stage: CI
    jobs:
      - job: DotNet
        steps:

        - task: UseDotNet@2
          displayName: 'Use .NET Core sdk'
          condition: ${{ parameters.usePreRelease }}
          inputs:
            packageType: sdk
            includePreviewVersions: true
            version: 5.0.100-preview.4.20258.7
            installationPath: $(Agent.ToolsDirectory)/dotnet
        
        - ${{ each step in parameters.preBuildSteps  }}:
            - ${{ each pair in step }}:
                ${{ pair.key }}: ${{ pair.value }}

        - task: DotNetCoreCLI@2
          displayName: Publish web app
          inputs:
            command: 'publish'
            zipAfterPublish: true
            projects: ${{ parameters.projectPath }}
            arguments: '-o $(Build.ArtifactStagingDirectory)/toDeploy'

        # - script: |
        #     cp pipelines/linux.service $(Build.ArtifactStagingDirectory)/toDeploy
        #   displayName: Copy Linux Service

        - task: PublishBuildArtifacts@1
          displayName: Prep for release
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'

  - stage: DeployDev
    displayName: 'Deploy to Development'

    jobs:
      - deployment: DevDeploy
        displayName: Deploy to Development VM
        environment:
          name: Development
          resourceType: VirtualMachine
          resourceName: websites
        strategy:
          runOnce:
            deploy:
              steps:

                - script: |
                    mkdir $(Pipeline.Workspace)/prep
                    cp -a $(Pipeline.Workspace)/drop/toDeploy/. $(Pipeline.Workspace)/prep
                    cd $(Pipeline.Workspace)/prep
                    echo ${{ serviceTemplate }} > $(Pipeline.Workspace)/prep/linux.service
                  displayName: Copy service file
                
                - ${{ each config in parameters.configs }}:
                  - script: 'echo "Environment=${{ config.key }}=''${{ config.value }}''" >> $(Pipeline.Workspace)/prep/linux.service'
                    displayName: Adding configuration for ${{ config.key }}

                - script: |
                    cd $(Pipeline.Workspace)/prep
                    sudo rm -rf ${{ destDirectory }}
                    sudo unzip ${{ projectName }}.zip -d ${{ destDirectory }}

                    sudo mv linux.service /etc/systemd/system/${{ parameters.service.name }}.service -f

                    sudo systemctl enable ${{ parameters.service.name }}.service 
                    sudo systemctl stop ${{ parameters.service.name }}.service 
                    sudo systemctl start ${{ parameters.service.name }}.service

                    cd ..
                    rm -rf $(Pipeline.Workspace)/prep
                  displayName: Updating website
                
            
    